README.md

Adds the missing closing braces `}}` in the README example.

fix typo in example

---

demo/app/states/root/components/data/examples.js
src/run/formlyNgModelAttrsManipulator.test.js

I recently was struggling to understand how to use ngModelAttrsManipluator to set a dynamic ng-required.
So I added a unit test and a new jsbin example (as requested in #156 ;-))
A fresh new PR with only a single commit! [Stack Overflow](http://stackoverflow.com/questions/5256021/send-a-pull-request-on-github-for-only-latest-commit) FTW!

Added unit tests and example for ng-required

---

src/directives/formly-field.js
src/directives/formly-field.test.js
src/providers/formlyApiCheck.js

Allows template and templateUrl properties of both a field type or field definition be functions.
Use case: A select type that uses a custom select directive such as ui-select which can be a single or multiple select which require different templates.

Allows template and templateUrl to be functions.

---

src/providers/formlyConfig.js
src/providers/formlyConfig.test.js

`templateUrl` is no longer ignored when extending a type which defines `template`
This also fixes the inverse.
Fixes #288

`templateUrl` is no longer ignored when extending a type which defines `template`

---

src/directives/formly-field.js
src/directives/formly-field.test.js

Added support for allowing 'template' property to be an empty string.
Would have allowed templateUrl to also be an empty string too but doing causes errors when the templateUrl is attempted to be loaded.
Fixes #285

Added support for allowing 'template' property to be an empty string.

---

src/directives/formly-field.js
src/directives/formly-field.test.js
src/run/formlyNgModelAttrsManipulator.js

Some templates may use a data-ng-model attribute instead of a ng-model attribute. This PR update the query selector in order to include those nodes.

add support for data-ng-model in custom templates

---

src/directives/formly-form.js

When the form group is uninitialized but `resetModel` or `updateInitialValue` is called, an error is raised because the field is not initialized with the options property as yet. This can happen if the form group has a `hideExpression` which removes it from the DOM initially and `formly-field` directive hasn't extended it with the options property as yet.
To fix this we need a property that identifies that the field has been properly initialized. The `options` property fulfils this role, so I'm checking it accordingly for both these functions.

Fixed bug from uninitialized form group

---

src/directives/formly-form.js
src/directives/formly-form.test.js

Yes, there are three commits apparently in this PR. I realized that you said the wrong issue number in your instructions, so I went back to amend the commit to reference #398 correctly.
Hope I did this correctly! :)

Added ability to add custom class to ngTransclude. Fixes #398.

---

src/directives/formly-field.js
src/directives/formly-field.test.js
src/directives/formly-form.js
src/directives/formly-form.test.js

I created a new pull request, I had some problem with merging and line endings, so I done it from scratch.
It adds the second test (from hidden to visible) and a optimization of model watchers (with test as well).

Fixed #380 - hideExpression is now called on field's model change; optimized number of field model watchers (one per object

---

src/directives/formly-form.js
src/directives/formly-form.test.js
src/other/utils.js
src/other/utils.test.js

Creating a nested model by specifying a field model as string starting with `model.` does not add a watcher.

Fixes #426: Support for nested model attribute (watcher optimization)

---

src/directives/formly-form.js
src/directives/formly-form.test.js

Changed restrictions on formly-form directive to allow usage as an attribute, tests pass.
Also noted ill formed HTML in the test (likely from copy & paste) and corrected in separate commit.

Formly-Form Directive as Attribute

---

other/ERRORS_AND_WARNINGS.md
src/directives/formly-form.js
src/directives/formly-form.test.js
src/providers/formlyApiCheck.js

Documentation and deprecation warnings for both options and formConfig.extras
Fixes #458

feat(formly-form): Use arrays for fieldTransforms

---

src/directives/formly-custom-validation.js

Fixes issues running formly in PhantomJS.  Other browsers may also have been affected.

fix(formly): Switched from using `Function.bind` to `angular.bind` to support more browsers

---

src/directives/formly-field.js
src/directives/formly-field.test.js
src/directives/formly-form.js

As runExpressions happens on NextTick return a promise and then validate. If there is no promise, just validate straight away

feat(formly-form): validate field after expressions are run

---

src/providers/formlyConfig.js

This fix removes the need to write formlyConfig.extras.fieldTransform =
formlyConfig.extras.fieldTransform || []; and instead adds an empty array as a default value for
fieldTransform.
closes #517

fix(formlyConfig.js): added a default for fieldTransform

---

src/directives/formly-field.js
src/directives/formly-form.test.js

The  shortcut is expected to be available in the template for fieldGroups now that they accept
wrappers.

fix(fieldGroup): add shortcut for templateOptions

---

src/providers/formlyValidationMessages.js

This should fix setting {min: 0} in field templateOptions to return proper message. I am not sure about the purpose of the alternate message.

Fix validation messages when comparing falsy value

---

src/directives/formly-field.test.js
src/directives/formly-form.js

Updated getwatchexpression function to handle deep dives

fix(formly-field): Watch does not work on deep properties #542

---

src/directives/formly-field.test.js

test(formly-field): should run field expressions when form is initialised

---

src/directives/formly-field.js
src/directives/formly-form.js
src/directives/formly-form.test.js
src/providers/formlyApiCheck.js

This is a proposal draft of a functionality that speeds up forms with very complex models. It works on my application at work :)
Problem: I have model that is extremely large (over 500KB) and multiple forms that I need this model to be passed to (over 10). There is a deep watcher created for every formly-form instance (so it's over 10) that watches the same model on every digest cycle.
So I did some digging:
This deep watcher is created in the FormlyFormController and is needed to fire formly expressions (hide, validations and custom expressions). I know exactly what fields from the model can trigger these expressions to be changed but formly is watching the whole model anyway, even if I don't have any expression or validation.
Solution: 
I added an option to manually define parts of …

adds manualModelWatcher option

---

CONTRIBUTING.md

[conventional-changelog](https://github.com/ajoslin/conventional-changelog) was recently [broken down into smaller modules](https://github.com/ajoslin/conventional-changelog/commit/48580b039197f45574f309b1c2ade18c17c2933b). 
During this change, the convention specs were deleted. This caused links to the Angular spec in [`CONTRIBUTING.md`](https://github.com/formly-js/angular-formly/blob/master/CONTRIBUTING.md) to break.
This pull request expands the existing Angular convention spec links to their canonical form.

Update links to Angular convention specification

---

src/directives/formly-field.test.js
src/directives/formly-form.js

Fix for issue #523
Bug fix
If field.formControl is an array, then call $validate method of each element
Checklist:

fix(formly-form): validateOnModelChange now copes when field.formControl is an array #523

---

src/directives/formly-form.js
src/directives/formly-form.test.js

Previously discussed on my previous PR https://github.com/formly-js/angular-formly/pull/599#issuecomment-172775380
**expect breaking change**
String hideExpression and watchers were evaluated in context of `$scope.model` unlike expressionProperties that were evaluated in the context of the model of a field. That said when you had nested model like `const model = {nested: {foo: 'bar'}};` and your field would have model declared as a string `model: 'model.nested'` your hideExpression and watcher would vary from expressionProperties:
```
hideExpression: 'model.nested.foo === "bar"'
expressionProperties: {
'some.property': 'model.foo === "bar"'
},
watcher: {
expression: 'model.nested.foo === "bar"',
listener: function() {}
}
```
After my tweaks, watchers and hideExpressions that are …

fix relative string models in hideExpression and watchers

---

src/directives/formly-form.js
src/directives/formly-form.test.js

String field models were resolved just once on init and when the outer model ($scope.model) is totally overridden, the field's model still references the old model. 
I have added a shallow reference watcher to every field that has string model. It checks if the reference changed and updates `field.model` accordingly.
I had to add 5th parameter to `evalCloseToFormlyExpression` because I didn't want to override the `field` object on each watcher. This might seem a bit dirty :+1: 
Test case for the fix added.
Checklist:

fix(models): update field model reference for fields with nested string models

---

src/directives/formly-form.js
src/directives/formly-form.test.js

Fix for issue #656
I did not take into account such basic scenario - no test case was failing and it all seemed to work on my app
`field` object does not contain `model` property that is the model itself for the basic field usage where the model is `$scope.model`. I assumed we could then assign this `$scope.model` as a property to `field` object and operate only on this property. This would make it consistent with the scenarios when `field.model` was passed as a string and resolved to an object (with a watcher) or assigned as an custom object.
This was a mistake because when `scope.model` reference changed, `field.model` referenced old model object. To make it work I would have to put a watcher on `scope.model` and update `field.model` accordingly but this would add a lot of unnecessary …

fix(model): keep track of correct model reference

---

src/directives/formly-field.js
src/directives/formly-field.test.js

Change check in `parseSet()/parseGet()` to permit a numeric 0 key.
Looking at `parseSet()/parseGet()`, the intended behavior seems to be that numeric keys mean array indexes. However, `parseSet()/parseGet()` will return prematurely if a `0` key is used.
Modified the check to permit `0` (and keep existing behavior for all other falsy values).
For issue #658

fix(formly-field): fixed check in parseSet/parseGet to permit 0 keys

---

src/providers/formlyConfig.js
src/providers/formlyConfig.test.js

Adding a `getTypes()` method to `formlyConfigProvider` that returns the map of type to config.
For a plugin I am writing that renders an inspector showing the current configuration for formly, I
need access to the types that have been registered with formly.
This change exposes the map of type name to type configuration object via a new method on `formlyConfigProvider` called `getTypes()`.
For issue #663
Checklist:

feat(formlyConfigProvider): Expose field types map from formlyConfigProvider

---

src/providers/formlyConfig.js
src/providers/formlyConfig.test.js

When the defaultOptions of a type are defined as a function and a different type extends it, the defaultOptions of the extending type are not correct.
It is a bug.
The ordering in the reverseDeepMerge() function was reversed and the incorrect object was being returned.  This change flips the parameters and returns the correct object.
For issue #635 
Checklist:
* [x ] Follows the commit message [conventions](https://github.com/stevemao/conventional-changelog-angular/blob/master/convention.md)
* [x ] Is [rebased with master](https://egghead.io/lessons/javascript-how-to-rebase-a-git-pull-request-branch?series=how-to-contribute-to-an-open-source-project-on-github)
* [x ] Is [only one (maybe two) commits](https://egghead.io/lessons/javascript-how-to-squash-multiple-git-commits)
Fix the …

fix(formlyConfig): fix defaultOptions override behavior

---

src/directives/formly-form.controller.js

In FormlyFormController in function validateFormControl variable validate was invoked with "undefined" this if the function was called with a promise.
It's a bug.
Used a closure and apply() to ensure validate() will be called with formController as this.
For issue #523 
Checklist:
Fixes validate being called with undefined this variable scope.
Closes #523

fix(FormlyFormController): Fix validateOnModelChange not firing with promise change #523
