formly-js/angular-formly

- src/directives/formly-custom-validation.js
- src/directives/formly-field.js
- src/directives/formly-focus.js
- src/directives/formly-form.js
This pull request resolves issue 191. It has the following changes:
- adds restrict property to formlyCustomValidation and formlyFocus directives;
- adds JSDoc comments to formlyField and formlyForm directives.
> resolve issue 191

- README.md
So that it's easier to get started :)
> Updated readme.md with vm convention and <form> tag

- demo/app/states/root/components/data/examples.js
New example of how to use input add-ons on formly fields
> Input add-ons example

- src/directives/formly-field.js
- src/directives/formly-field.test.js
…e options when the ng-model was placed on a div. See http://jsbin.com/cicuri/3/edit?html,js to reproduce.
I also added a now passing test
> Fixing an issue where the form controller wasn't being assigned to the options when ng-modelw as placed on a div

- src/directives/formly-field.test.js
Turns out, there was no problem with the production code.
> fix for #300

- src/directives/formly-field.js
- src/directives/formly-field.test.js
- src/test.utils.js
> feature(formyField): Added support for fields with multiple elements having ngModels.

- src/directives/formly-field.js
- src/providers/formlyApiCheck.js
- src/run/formlyNgModelAttrsManipulator.js
- src/run/formlyNgModelAttrsManipulator.test.js
Issue https://github.com/formly-js/angular-formly/issues/341
@kentcdodds please take this PR with caution as it can be completely wrong, most of all I would like to know your feedback, for my own benefit on learning formly's architecture.
> Issue #341

- src/directives/formly-field.js
- src/directives/formly-field.test.js
> Solves #347

- src/providers/formlyApiCheck.js
feature(formyField): #327 added multiple formControls. 
the apicheck on fieldOptionsApiShape is still missing the this feature though
> allow arrays on fieldOptionsApiShape.formControl

- src/directives/formly-form.js
> Add support for attributes prefixed with `data-`

- .gitattributes
Use gitattributes to normalize line endings to lf
> chore(gitattributes): text=auto on checkout

- src/directives/formly-field.test.js
> test(defaultValue): failing test for nested keys

- src/directives/formly-field.js
- src/directives/formly-field.test.js
defaultValue now uses $parse to set keys
refs #468
> fix(defaultValue): fix nested keys to work with default values

- package.json
:rocket:
One of your dependencies has just updated, so this PR bumps the corresponding version number in your `package.json`.
You can now check that the dependency update doesn't break your code, and then release the new version of your software safe in the knowledge that it will stay in this working state, regardless of _when_ your users do `$ npm install`.
Have a good day!
---
This pull request was created by [greenkeeper.io](http://greenkeeper.io/).
It keeps your software, up to date, all the time.
<sub>
Tired of seeing this sponsor message? Upgrade to the supporter plan!
You'll also get your pull requests faster :zap:
</sub>
> Updated http-server to version 0.8.5

- src/index.test.js
- src/run/formlyCustomTags.test.js
:arrow_up: Coverage :arrow_up:
> test(formly-run): stub and test for addCustomTags

- src/directives/formly-field.js
- src/directives/formly-form.test.js
- src/providers/formlyApiCheck.js
fixes #486 & #528 
Working example: http://jsbin.com/zaqeke/21/edit?html,js,output
> feat(fieldGroup): allow wrapper & templateOptions

- src/directives/formly-field.js
- src/directives/formly-field.test.js
Updated code to check for digits and alpha numerics
> fix(formly-field): Breaking change in @7.3.2? Key value? #566

- src/directives/formly-field.js
- src/directives/formly-field.test.js
Updated the resetModel function to set call  on the form as well as the fields
#574
> fix(resetModel): Updated resetModel to set the form to pristine

- other/webpack.config.es6.js
- package.json
> fix(webpack): add UglifyPlugin

- gulpfile.js
- package.js
- package.json
@kentcdodds All you have to do is to add a webhook `https://autopublish.meteor.com/publish` with `Release` event
> Support for meteor

- src/directives/formly-form.js
- src/directives/formly-form.test.js
- src/providers/formlyApiCheck.js
originally requested in:
http://stackoverflow.com/questions/34850697/clearing-fieldgroups-fields-when-hidden/34857087?noredirect=1#comment57499232_34857087
> feat(formly-form): add 'watcher' to fieldGroup
